# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575a296208f9bb6ab3dce182989f22c6d2a5740fb298b783526e8daef5c59f56089c29ae2415354c50a98788bba89e42bdda98c3d2a7438ea505ea944a50c57f

test:
  secret_key_base: 8c44cd8bc16b8605659468d5fa438b2091a631e02e26bf06df99b8b0479bfaab29416df34319f61bff9031b5f5bafad1f54ceaaaac7237c990baa84c6e36e493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
